### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by lj17525194100** [zmzhang/IOS#1]
How should I set up  Mtrain and outF parameters in IOS.M

**Comment by zmzhang** [comment]
Hi @lj17525194100 

Thanks for your feedback!

(1) mTrain parameter
mTrain is the number of samples, which are selected as the training set.

(2) outF parameter
outF parameter is the anomaly scores of samples calculated by  AnomalyScore function in  IsolationForest package.
You can calculate it using this script: 
    https://github.com/zmzhang/IOS/blob/master/IOS.r
The definition of AnomalyScore function is as following:
    https://rdrr.io/rforge/IsolationForest/man/AnomalyScore.html
 
Regards,
Zhimin
